name: seyahat_haritasi_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # TÜM TEMİZLENMİŞ, EN GÜNCEL STABİL VERSİYONLAR
  flutter_map: ^8.2.2          
  latlong2: ^0.9.1             
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  path: ^1.9.1
  # flutter_map_geojson'u tamamen çıkardık



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# BURADAN BAŞLAYAN KISIM (assets) HAYATİ ÖNEM TAŞIR
flutter:
  uses-material-design: true
  
  # Assets (Veri Dosyası) Yolu Tanımlaması:
  assets:
    - assets/world.geojson
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic